run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - misspell
    - gocyclo
    - godot
    - revive
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: false
  goimports:
    local-prefixes: github.com/jeanGouveia/horizongest/backend
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
