-- +goose Up
-- +goose StatementBegin

-- Sprint 4C: Add idempotency key to orders table
-- This prevents duplicate order creation on POST retries (F5, network timeout, etc.)
-- The idempotency key is generated by the client (or server) and must be unique per company
-- When a duplicate idempotency key is received, the existing order is returned instead of creating a new one

-- Add idempotency_key column
ALTER TABLE orders ADD COLUMN idempotency_key VARCHAR(255);

-- Add unique index on (company_id, idempotency_key) to prevent duplicates within a company
-- NULL values are allowed for existing orders (backward compatibility)
CREATE UNIQUE INDEX uk_orders_company_idempotency_key 
ON orders(company_id, idempotency_key) 
WHERE idempotency_key IS NOT NULL;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Remove unique index
DROP INDEX IF EXISTS uk_orders_company_idempotency_key;

-- Remove idempotency_key column
ALTER TABLE orders DROP COLUMN IF EXISTS idempotency_key;

-- +goose StatementEnd
